### ISSUE TITLE
QUIC_CRYPTO_TOO_MANY_REJECTS

### ISSUE THREAD

**Issue by typcn** [devsisters/gospdyquic#2]
I build a simple quic server using gospdyquic

but when I try to visit using chrome, It was connected using HTTP/2 

alternative service mapping show it's "broken" and the console show error "QUIC_CRYPTO_TOO_MANY_REJECTS"

**Comment by serialx** [comment]
Did you use a SSL certificate? If so, can you check if it uses an ECDSA private key? There's a untested code in gospdyquic that is triggered if an ECSDA cert is used. See:

https://github.com/devsisters/gospdyquic/blob/master/spdyquic.go#L264

**Comment by typcn** [comment]
Sorry I'm not read the spec.
I'm using RSA certificate.maybe I need buy a new one.
Thanks

**Comment by serialx** [comment]
If you're using RSA key, it should work fine. Maybe you are not connecting to the server with correct hostname? Also try connecting to the server without SSL certificate and see if it works.

**Comment by typcn** [comment]
Yes , The hostname is correct , HTTP/2 HTTP/1.1 works fine.
My chrome seems not connect QUIC without SSL.

**Comment by serialx** [comment]
Can you try with the latest code? We've fixed some bugs, so it might work this time.

Thanks!

**Comment by typcn** [comment]
I have rebuild all libraries using latest code , still got same error

**Comment by typcn** [comment]
I have saved all output logs, how can I send to you ?

**Comment by typcn** [comment]
Both HTTP and HTTPS works on my mac .
but on linux VM , HTTP return code is 500, and HTTPS is "QUIC_CRYPTO_TOO_MANY_REJECTS "

**Comment by serialx** [comment]
You can use https://gist.github.com/ to send logs to me. I'll have a look at it.

So you are only having problems on linux VM, is that correct?

**Comment by typcn** [comment]
Yes

Log: https://gist.github.com/typcn/4d3e14282eaf06f9b007

**Comment by typcn** [comment]
WWWTTTFFF

I try to run the server without any modification today.
and it works well .....
I will try to integrate it with nginx.

Thanks

**Comment by serialx** [comment]
:) Closing issue.
