### ISSUE TITLE
ERR_QUIC_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by nickrace** [devsisters/gospdyquic#4]
Firstly, great job in pulling together this set of libraries and then making a Go implementation available.

Now, onto the issue I've been having.  I've successfully compiled the qoquic library and built the gospdyquic example server to start testing with.  Using Chrome 43.0.2357.134 to access the server via HTTP on port 8080 it returns "ERR_QUIC_PROTOCOL_ERROR".  Looking at chrome://net-internals I can see that a QUIC session to the server is indeed reported, so it's clear that some communication via QUIC is taking place.

I'd welcome any suggestions as to the potential cause - which could well be down to a configuration issue on my part.  I can happily post logs from both Chrome & the server if that would help identify the issue.

**Comment by kuss** [comment]
Hello, please try again with Chrome Canary (>= 46.0.2461.0). Maybe some updates on QUIC protocol have not applied to current version of chrome (<= 43.0.2357.134)

**Comment by hodduc** [comment]
I found that there is an issue with protocol version 24, which is default on chrome 43.0. (and trying to fix it :) ) Chrome Canary uses protocol version 25 so using Canary will hopefully solve your problem.

**Comment by hodduc** [comment]
I found an issue and fixed it on https://github.com/devsisters/goquic/commit/c7c942117e39525b6293d1dc49de908a6d2a40fb . Would you please try it again?

**Comment by nickrace** [comment]
That's working now with Chrome 43.0 - thanks!

**Comment by PenelopeWatson629bn** [comment]
Check Firewall or Proxy Settings
Set to auto detect settings
Win+r type "inetcpl.cpl" without quote"
>Connection
>LAN settings
>Only Check Box Automatically detect settings
Or follow this steps below
https://www.errorsolutions.tech/error/err_quic_protocol_error/
Solution 1. Disable Experimental QUIC protocol
